- hosts: a
  
  vars:
    - port: 80
  
  tasks:
    - name: 'touch file'
      copy: src=/tmp/123.txt dest=/tmp/{{port}}.txt
      when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "5") or
            (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or
            (ansible_os_family == "Debian")
    - name: 'install 3 pak list'
      yum: name={{item}} state=absent
      with_items:
        - 'httpd'
        - 'mysql-devel'
        - 'lrzsz'
          


