- name: Copy File
  copy:
    src: jdk-8u161-linux-x64.tar.gz
    dest: /usr/local/src/jdk-8u161-linux-x64.tar.gz
- name: Unzip jdk
  unarchive:
    src: /usr/local/src/jdk-8u161-linux-x64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: link jdk
  file:
    src: /usr/local/jdk1.8.0_161/
    dest: /usr/local/jdk
    state: link
    owner: root
    group: root
    mode: 0755


- name: set JAVA ENV
  lineinfile:
    dest: /etc/profile
    line: '{{ item }}'

  with_items:
    - 'JAVA_HOME=/usr/local/jdk JRE_HOME=/usr/local/jdk/jre'
    - 'PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
    - 'CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib'
    - 'export JAVA_HOME JRE_HOME PATH CLASSPATH'




