- hosts: a
  tasks:
    - name: tag1
      shell: echo "tag1" >  /tmp/tag1.txt
      tags:
        - tag1


    - name: tag2
      shell: echo "tag2" >  /tmp/tag1.txt
      tags:
        - tag2




#
#zhoutao@zt:~/ansible-study/test_study$ ansible-playbook tags.yml --skip-tags=tag2   #跳过tag2
#
#PLAY [a] ************************************************************************************************************************************************************************************************************************************
#
#TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
#ok: [a]
#
#TASK [tag1] *********************************************************************************************************************************************************************************************************************************
#changed: [a]
#
#PLAY RECAP **********************************************************************************************************************************************************************************************************************************
#a                          : ok=2    changed=1    unreachable=0    failed=0
#
#zhoutao@zt:~/ansible-study/test_study$ ansible-playbook tags.yml --skip-tags=tag1
#
#PLAY [a] ************************************************************************************************************************************************************************************************************************************
#
#TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
#ok: [a]
#
#TASK [tag2] *********************************************************************************************************************************************************************************************************************************
#changed: [a]
#
#PLAY RECAP **********************************************************************************************************************************************************************************************************************************
#a                          : ok=2    changed=1    unreachable=0    failed=0
#

#
#zhoutao@zt:~/ansible-study/test_study$ ansible-playbook tags.yml --list-tags  # 查看所有tags

#
#playbook: tags.yml
#
#  play #1 (a): a        TAGS: []
#      TASK TAGS: [tag1, tag2]


#zhoutao@zt:~/ansible-study/test_study$ ansible-playbook tags.yml -t tag1 #单独执行某个tag
#
#PLAY [a] ************************************************************************************************************************************************************************************************************************************
#
#TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
#ok: [a]
#
#TASK [tag1] *********************************************************************************************************************************************************************************************************************************
#changed: [a]
#
#PLAY RECAP **********************************************************************************************************************************************************************************************************************************
#a                          : ok=2    changed=1    unreachable=0    failed=0
